/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/workspace/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateWorkspaceCommand"];
                    "text/json": components["schemas"]["CreateWorkspaceCommand"];
                    "application/*+json": components["schemas"]["CreateWorkspaceCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfCreateWorkspaceResult"];
                        "application/json": components["schemas"]["ResultOfCreateWorkspaceResult"];
                        "text/json": components["schemas"]["ResultOfCreateWorkspaceResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterCommandRequest"];
                    "text/json": components["schemas"]["RegisterCommandRequest"];
                    "application/*+json": components["schemas"]["RegisterCommandRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Result"];
                        "application/json": components["schemas"]["Result"];
                        "text/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginCommandRequest"];
                    "text/json": components["schemas"]["LoginCommandRequest"];
                    "application/*+json": components["schemas"]["LoginCommandRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Result"];
                        "application/json": components["schemas"]["Result"];
                        "text/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Result"];
                        "application/json": components["schemas"]["Result"];
                        "text/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfUserProfileResult"];
                        "application/json": components["schemas"]["ResultOfUserProfileResult"];
                        "text/json": components["schemas"]["ResultOfUserProfileResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfGetUserWorkspacesResult"];
                        "application/json": components["schemas"]["ResultOfGetUserWorkspacesResult"];
                        "text/json": components["schemas"]["ResultOfGetUserWorkspacesResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateWorkspaceCommand: {
            name: string;
            description: null | string;
            visibility: components["schemas"]["WorkspaceVisibility"];
        };
        CreateWorkspaceResult: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        GetUserWorkspaceResult: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            visibility: string;
            description: null | string;
            /** Format: int32 */
            totalMembers: number | string;
            /** Format: int32 */
            totalProjects: number | string;
            /** Format: date-time */
            updateAt: string;
            membersPreviews: components["schemas"]["WorkspaceMemberPreview"][];
        };
        GetUserWorkspacesResult: {
            /** Format: int32 */
            count: number | string;
            /** Format: int32 */
            totalMembers: number | string;
            data: components["schemas"]["GetUserWorkspaceResult"][];
        };
        LoginCommandRequest: {
            email: string;
            password: string;
        };
        RegisterCommandRequest: {
            username: string;
            email: string;
            password: string;
        };
        Result: {
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfCreateWorkspaceResult: {
            value?: components["schemas"]["CreateWorkspaceResult"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfGetUserWorkspacesResult: {
            value?: components["schemas"]["GetUserWorkspacesResult"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfUserProfileResult: {
            value?: components["schemas"]["UserProfileResult"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        UserProfileResult: {
            /** Format: uuid */
            id: string;
            username: string;
            email: string;
        };
        WorkspaceMemberPreview: {
            /** Format: uuid */
            userId: string;
            username: string;
        };
        /** @enum {unknown} */
        WorkspaceVisibility: "Public" | "Private";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
